### ISSUE TITLE
Setup travis to publish examples datasets

### ISSUE THREAD

**Issue by Mikanebu** [datahq/pm#32]
We want to have a `travis.yml` configured, so it will trigger `data push` automatically for examples datasets.  

## Acceptance criteria

* [x] Examples datasets are published by travis

## Tasks

* [x] Setup `.travis.yml` 

## Analyses 

All examples datasets are located here https://github.com/datapackage-examples
There are 3 main variables we need to push our data: `token, username, id` 

We can setup `.travis.yml` as follows: 
```
language: node_js
node_js:
- '8'
install:
- npm install -g git+https://github.com/datahq/datahub-cli.git
script: data push ./ --published
env:
  global:
    id: ID
    username: USERNAME
  TRAVIS_SECURE_ENV_VARS: true
```

Our `token` will be configured in the repo settings for travis.
